version: bcu_1.1.18

skip_tags: true

#- switched to 2017 for now because VS 2019 imagines does not have coverity build tool
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
  bcu_coverity_token:
    secure: YuctP7YsJQIzsrBQtgEfwkYPu3StAEWV9SgPIBjwZDo=

platform:
- x64

configuration: 
- Release

init:
# skip x86 check in linux  
- sh: if [ "${PLATFORM}" = "x86" ]; then exit 0; fi
- sh: if [ "${CONFIGURATION}" = "Debug" ] ; then exit 0; fi

install:
# - sh: sudo apt-get update
- cmd: git submodule update --init
- sh: git submodule update --init
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  update); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libconfuse-dev swig python-dev libboost-all-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libyaml-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install openssl); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  update); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libconfuse-dev swig python-dev libboost-all-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libyaml-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install libusb-1.0-0-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (sudo DEBIAN_FRONTEND=noninteractive apt-get  --yes --force-yes install openssl libssl-dev); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "macOS" ]; then ( brew reinstall pkgconfig; export PATH="/usr/local/Cellar/pkg-config/0.29.2_3/bin:${PATH}"; brew reinstall libyaml openssl; brew install libftdi; ln -s /usr/local/Cellar/openssl@1.1/1.1.1i/lib/pkgconfig/*.pc /usr/local/lib/pkgconfig/; pkg-config --list-all;); fi

build_script:
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (cmake .); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (cmake .); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "macOS" ]; then (export PATH="/usr/local/Cellar/pkg-config/0.29.2_3/bin:${PATH}"; cmake .); fi
- sh: make
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu1604" ]; then (mv bcu bcu_Ubuntu1618); fi
- sh: if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" = "Ubuntu2004" ]; then (mv bcu bcu_Ubuntu20); fi

# no schedule coverity check:
#- cmd: cov-build --dir cov-int msbuild %APPVEYOR_BUILD_FOLDER%/Board_Control_Utilities.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# scheduled coverity check:
- cmd: if "%APPVEYOR_SCHEDULED_BUILD%" == "True" (cov-build --dir cov-int msbuild %APPVEYOR_BUILD_FOLDER%/Board_Control_Utilities.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll") else (msbuild %APPVEYOR_BUILD_FOLDER%/Board_Control_Utilities.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll")
- cmd: if "%APPVEYOR_SCHEDULED_BUILD%" == "True" (7z a -tzip bcu.zip cov-int)
- cmd: if "%APPVEYOR_SCHEDULED_BUILD%" == "True" (curl --form token=%bcu_coverity_token% --form email=frank.li@nxp.com  --form file=@bcu.zip --form version="appveyor_upload"  --form description="attempt to automate coverity scan" https://scan.coverity.com/builds?project=NXPmicro%2Fbcu)

# get artifact:
- cmd: if exist %APPVEYOR_BUILD_FOLDER%\x64\Release\Board_Control_Utilities.exe  (cp %APPVEYOR_BUILD_FOLDER%\x64\Release\Board_Control_Utilities.exe  %APPVEYOR_BUILD_FOLDER%\bcu.exe)

artifacts:
- path: bcu.exe
- path: bcu_Ubuntu1618
- path: bcu_Ubuntu20
- path: bcu_mac

before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  description: prebuild for $(APPVEYOR_REPO_COMMIT) \n\n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: SWWVkwSfPyVIaPChBBl+uAA3Fau9Rl5iNPQ9VRL8yyggXvc6wPcr/O9iXBMVM7Ju
  artifact: bcu.exe;  bcu_Ubuntu1618;  bcu_Ubuntu20;  bcu_mac;
  draft: true
